<a href="https://colab.research.google.com/github/Zain-mahfoud94/Python-Uni/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
print(torch.__version__)

2.5.1+cu121


## introduction to Tensors

### creating tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.item())

tensor(7)
0
7


In [ ]:
# vector
vector = torch.tensor([7,7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8], [9,10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX[0])

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])
tensor([7, 8])


In [ ]:
# TENSOR
TENSOR = torch.tensor([[[7,8,9], [10,11,12], [13,14,15]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0])

tensor([[[ 7,  8,  9],
         [10, 11, 12],
         [13, 14, 15]]])
3
torch.Size([1, 3, 3])
tensor([[ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])


### Random Tensors

In [ ]:
#Random tensors
random_tensor = torch.rand(3,4)
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)
# Random tensors with shape like images
random_image_size_tensor = torch.rand(size=(224,224,3))
print(random_image_size_tensor.shape)

tensor([[0.4142, 0.6982, 0.2129, 0.7097],
        [0.9646, 0.9248, 0.6765, 0.0678],
        [0.3543, 0.9063, 0.9171, 0.1277]])
2
torch.Size([3, 4])
torch.Size([224, 224, 3])


### create zeros and ones tensors

## create zeros

In [ ]:
zeros_tensor = torch.zeros(size=(3,3))
print(zeros_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


## create ones

In [ ]:
ones_tensor = torch.ones(size=(3,3))
print(ones_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
ones_tensor.dtype

torch.float32

### Create a range of tensors and tensors-like

# user torch.arange()

In [ ]:
one_to_ten = torch.arange(0,11,2)
one_to_ten

tensor([ 0,  2,  4,  6,  8, 10])

## Creating tensors like

In [ ]:
tensor_like = torch.zeros_like(one_to_ten)
tensor_like

tensor([0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [ ]:
#Float 32 tensor
float_32_tensor = torch.tensor([3,6,9], dtype=torch.float32, device= None, requires_grad=False)
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)

In [ ]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting Information from tensors

In [ ]:
# Create a tensor
tensor = torch.rand(3,4, dtype=torch.float16, device=torch.device("cuda"))
tensor

tensor([[0.3384, 0.1471, 0.7207, 0.9521],
        [0.4395, 0.6001, 0.5381, 0.9590],
        [0.4993, 0.0225, 0.5664, 0.6538]], device='cuda:0',
       dtype=torch.float16)

# shape

In [ ]:
tensor.shape, tensor.size()

(torch.Size([3, 4]), torch.Size([3, 4]))

# data type

In [ ]:
tensor.dtype

torch.float16

# device

In [ ]:
tensor.device, tensor.is_cpu, tensor.is_cuda

(device(type='cuda', index=0), False, True)

### Manipulating Tensors (Tensor Operations)

In [ ]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

## Addition

In [ ]:
tensor + 10

tensor([11, 12, 13])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

## Subtraction

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
torch.sub(tensor,10)

tensor([-9, -8, -7])

## Multiplication (element-wise)

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
torch.mul(tensor,10)

tensor([10, 20, 30])

## Division

In [ ]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
torch.div(tensor,10)

tensor([0.1000, 0.2000, 0.3000])

## Matrix multiplication (dot product)

In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
## time
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.16 ms, sys: 30 µs, total: 1.19 ms
Wall time: 3.31 ms


tensor(14)

In [ ]:
## time
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.19 ms, sys: 35 µs, total: 1.23 ms
Wall time: 3.37 ms


tensor(14)

### one of the most common errors in deep learning: shape errors

In [ ]:
# Shapes for matrix multiplucations
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])
torch.mm(tensor_A,tensor_B.T).shape

torch.Size([3, 3])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
tensor = torch.arange(0,100,10)
tensor, tensor.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
torch.min(tensor), tensor.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(tensor), tensor.max()

(tensor(90), tensor(90))

In [ ]:
torch.mean(tensor.type(torch.float32)), tensor.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(tensor), tensor.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [ ]:
torch.argmax(tensor), tensor.argmax()

(tensor(9), tensor(9))

In [ ]:
torch.argmin(tensor), tensor.argmin()

(tensor(0), tensor(0))

### Reshaping, stacking, squeezing, unsqueezing
* Reshaping - reshapes an input tensor to a defined shape.
* View - Return a view of an input tensor of certain shape but keep the same memory as the orignal tensor.
* Stacking - combine multiple tensors on top of each other (vstacK) or side by side (hstack).
* Squeez - remove all `1` dimensions from a tensor.
* Unsqueez - add a `1` dimension to a target tensor.
* Permute - return a view of the input with dimensions permuted (swapped) in a certin way.

In [ ]:
x = torch.arange(1,10,1)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
z = x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
# changin z chages x ( beacause a view of a tensor shares the same memory as the origianl tensor)
z[:,0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

# stack tensors on top of each others

In [ ]:
x_stacked_v = torch.stack([x,x,x,x], dim = 0)
x_stacked_v, torch.vstack([x,x,x,x])

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9]]),
 tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9]]))

In [ ]:
x_stacked_h = torch.stack([x,x,x,x], dim = 1)
x_stacked_h, torch.hstack([x,x,x,x])

(tensor([[5, 5, 5, 5],
         [2, 2, 2, 2],
         [3, 3, 3, 3],
         [4, 4, 4, 4],
         [5, 5, 5, 5],
         [6, 6, 6, 6],
         [7, 7, 7, 7],
         [8, 8, 8, 8],
         [9, 9, 9, 9]]),
 tensor([5, 2, 3, 4, 5, 6, 7, 8, 9, 5, 2, 3, 4, 5, 6, 7, 8, 9, 5, 2, 3, 4, 5, 6,
         7, 8, 9, 5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
x_squeeze = torch.squeeze(x)
x_squeeze, x_squeeze.shape

(tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
x_unsqueeze = torch.unsqueeze(x_squeeze, dim=0)
x_unsqueeze, x_unsqueeze.shape

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
x_unsqueeze = torch.unsqueeze(x_squeeze, dim=1)
x_unsqueeze, x_unsqueeze.shape

(tensor([[5],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [ ]:
x_original = torch.rand(size=(224,224,3))
x_permute = torch.permute(x_original, dims=(2,0,1))
x_original.shape, x_permute.shape, x_original.permute(2, 0, 1).shape, x_original[0,0,0]

(torch.Size([224, 224, 3]),
 torch.Size([3, 224, 224]),
 torch.Size([3, 224, 224]),
 tensor(0.8437))

In [ ]:
x_original[0,0,0] = 0.2222
x_original[0,0,0], x_permute[0,0,0]

(tensor(0.2222), tensor(0.2222))

### Indexing

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0,0]

tensor([1, 2, 3])

In [ ]:
x[0,0,0]

tensor(1)

### PyTorch tensors and NumPy

In [ ]:
# NumPy array to tensor
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the value of array, what will this do to "tensor"
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
numpy_tensor, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([1., 1., 1., 1., 1., 1., 1.]))

In [ ]:
# Change the tensor, what happens to 'numpy_tensor"
tensor = tensor +1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducbility (trying to take ranom out of random)

In [ ]:
# Create two random tensors
random_1 = torch.rand(3,4)
random_2 = torch.rand(3,4)
print(random_1)
print(random_2)
print(random_1 == random_2)

tensor([[0.3335, 0.2709, 0.7086, 0.5775],
        [0.4202, 0.4008, 0.4348, 0.0747],
        [0.5677, 0.0533, 0.2541, 0.3692]])
tensor([[0.8080, 0.3396, 0.8665, 0.9418],
        [0.0310, 0.8481, 0.5430, 0.6844],
        [0.9130, 0.2770, 0.8706, 0.3108]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let us make some random but reproducible tensors
# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_a = torch.rand(3,4)
# should be called before each random generation
torch.manual_seed(RANDOM_SEED)
random_tensor_b = torch.rand(3,4)
print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and Pytorch object on the GPUs ( and making faster computations)

In [ ]:
!nvidia-smi

Fri Dec 13 18:09:05 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   77C    P0              33W /  70W |    121MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
# Check for GPU access with pyTorch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available else "cpu"
device

'cuda'

In [ ]:
# Count the number of devices
torch.cuda.device_count()

1

In [ ]:
### Putting tensors (and models) on the GPU
tensor = torch.tensor([1,2,3])
# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
### Moving tensors back to CPU
# gives error
#tensor_on_gpu.numpy() # if tensor is on GPU, can't transfrom it to NumPy

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu()
array = tensor_back_on_cpu.numpy()
array

array([1, 2, 3])

### Exercises